### ISSUE TITLE
After make....any help will be appreciated!!!

### ISSUE THREAD

**Issue by ghost** [PlatformLab/ramcloud-ycsb#1]
g++ --std=c++0x -g -DNDEBUG -I./ramcloud/include -I. -L./ramcloud/bin -lramcloud helper.cc -o helper -Wl,-rpath=./ramcloud/bin
In file included from ./ramcloud/include/ramcloud/PerfStats.h:22:0,
                 from helper.cc:21:
./ramcloud/include/ramcloud/SpinLock.h:50:18: error: ‘lock_guard’ in namespace ‘std’ does not name a template type
     typedef std::lock_guard<SpinLock> Guard;
                  ^
make: **\* [helper] Error 1

**Comment by johnousterhout** [comment]
Oops, there was a missing #include in RAMCloud's SpinLock.h. I just pushed a fix; if you pull a new version of the RAMCloud repo this problem should go away.

Sorry for the problem.

**Comment by cstlee** [comment]
Fixed in upstream dependency: https://github.com/PlatformLab/RAMCloud/commit/51b53933cc49b35b878c197b5db8d8570a01867f

**Comment by ghost** [comment]
Thanks! I'm having some reference issues, but the error was fixed.
