### ISSUE TITLE
Make....

### ISSUE THREAD

**Issue by ghost** [PlatformLab/ramcloud-ycsb#2]
I compiled RAMCloud and installed it onto a directory, made symbolic link inside ramcloud-ycsb to this folder and make. All libraries mentioned here are available in the include folder of ramcloud
Result of make: 

g++ --std=c++0x -g -DNDEBUG -I./ramcloud/include -I. -L./ramcloud/bin -lramcloud helper.cc -o helper -Wl,-rpath=./ramcloud/bin
/tmp/ccAtPwHr.o: In function `main':
ramcloud-ycsb/helper.cc:53: undefined reference to`RAMCloud::RamCloud::RamCloud(char const_, char const_)'
ramcloud-ycsb/helper.cc:56: undefined reference to `RAMCloud::Buffer::Buffer()'
ramcloud-ycsb/helper.cc:58: undefined reference to`RAMCloud::RamCloud::serverControlAll(RAMCloud::WireFormat::ControlOp, void const_, unsigned int, RAMCloud::Buffer_)'
ramcloud-ycsb/helper.cc:56: undefined reference to `RAMCloud::Buffer::~Buffer()'
ramcloud-ycsb/helper.cc:128: undefined reference to`RAMCloud::RamCloud::logMessageAll(RAMCloud::LogLevel, char const_, ...)'
ramcloud-ycsb/helper.cc:139: undefined reference to `RAMCloud::RamCloud::serverControlAll(RAMCloud::WireFormat::ControlOp, void const_, unsigned int, RAMCloud::Buffer_)'
ramcloud-ycsb/helper.cc:53: undefined reference to `RAMCloud::RamCloud::~RamCloud()'
ramcloud-ycsb/helper.cc:56: undefined reference to`RAMCloud::Buffer::~Buffer()'
ramcloud-ycsb/helper.cc:53: undefined reference to `RAMCloud::RamCloud::~RamCloud()'
ramcloud-ycsb/helper.cc:146: undefined reference to`RAMCloud::ClientException::str() const'
/tmp/ccAtPwHr.o: In function `RAMCloud::CodeLocation::str() const':
ramcloud-ycsb/./ramcloud/include/ramcloud/CodeLocation.h:41: undefined reference to`RAMCloud::CodeLocation::relativeFile() const'
ramcloud-ycsb/./ramcloud/include/ramcloud/CodeLocation.h:40: undefined reference to `RAMCloud::CodeLocation::qualifiedFunction() const'
ramcloud-ycsb/./ramcloud/include/ramcloud/CodeLocation.h:42: undefined reference to`RAMCloud::format(char const_, ...)'
/tmp/ccAtPwHr.o: In function `RAMCloud::Exception::str() const':
ramcloud-ycsb/./ramcloud/include/ramcloud/Exception.h:48: undefined reference to`RAMCloud::demangle(char const_)'
/tmp/ccAtPwHr.o:(.gcc_except_table+0x50): undefined reference to `typeinfo for RAMCloud::ClientException'
/tmp/ccAtPwHr.o: In function`RAMCloud::WireFormat::ServerControl::Response_ RAMCloud::Buffer::getOffsetRAMCloud::WireFormat::ServerControl::Response(unsigned int)':
ramcloud-ycsb/./ramcloud/include/ramcloud/Buffer.h:242: undefined reference to `RAMCloud::Buffer::getRange(unsigned int, unsigned int)'
/tmp/ccAtPwHr.o: In function`RAMCloud::PerfStats\* RAMCloud::Buffer::getOffsetRAMCloud::PerfStats(unsigned int)':
ramcloud-ycsb/./ramcloud/include/ramcloud/Buffer.h:242: undefined reference to `RAMCloud::Buffer::getRange(unsigned int, unsigned int)'
/tmp/ccAtPwHr.o: In function`RAMCloud::WireFormat::ServerControlAll::Response\* RAMCloud::Buffer::getOffsetRAMCloud::WireFormat::ServerControlAll::Response(unsigned int)':
ramcloud-ycsb/./ramcloud/include/ramcloud/Buffer.h:242: undefined reference to `RAMCloud::Buffer::getRange(unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
make: **\* [helper] Error 1

**Comment by cstlee** [comment]
I'm trying to reproduce this here but I'm running into a different build issue.  I'll post back when I have an update.

**Comment by cstlee** [comment]
I was able to resolve my previously mentioned build issue but am still not able to reproduce your build error.  You used the following command correct?

`g++ --std=c++0x -g -DNDEBUG -I./ramcloud/include -I. -L./ramcloud/bin -lramcloud helper.cc -o helper -Wl,-rpath=./ramcloud/bin`

**Comment by ghost** [comment]
Yes, exactly that line. My previous steps were compiling RAMCloud as the instructions on the wiki and then make install with an install directory that is used with a symbolic link made inside the ramcloud-ycsb folder that has the bin, include and lib folders. I still come up with the same error. I'm using an Ubuntu 14 virtual machine

**Comment by ghost** [comment]
It compiled:
First had to change the GNUmakefile to compile using this command:
g++ --std=c++0x -g -DNDEBUG -I/ramcloud/include -I.   helper.cc -o helper -L/ramcloud/bin -lramcloud -Wl,-rpath=/ramcloud/bin

where the linking library path is placed after the object file. After this, just updated the change that was placed on the repository for the same file.

**Comment by cstlee** [comment]
I'm glad you got this fixed.  For the benefit of others, was there a change here that should be committed back to the repository?

**Comment by ghost** [comment]
I did make this change on the GNUMakefile, changing the order of the $LIBS variable on the helper line.

helper: helper.cc $(RAMCLOUD_DIR)/bin/libramcloud.so
        $(CXX) $(CXXFLAGS) $(INCLUDES) helper.cc -o helper $(LIBS) -Wl,-rpath=$(BIN_DIR)
